### ISSUE TITLE
iis部署后，登录失败未跳转

### ISSUE THREAD

**Issue by langhaoabcd** [linianhui/oidc.example#43]
感谢大佬的例子，实用性非常强。有两个问题请教下，这是用直接源码部署的没动过
1. 客户端未登录跳转到oidc server，点击了登录还在原地没跳转回去，是什么情况？
![image](https://user-images.githubusercontent.com/39892654/118993411-14432d80-b9b8-11eb-846b-4d223b3494b3.png)
![image](https://user-images.githubusercontent.com/39892654/118993634-42c10880-b9b8-11eb-9ef4-1bed4927a80a.png)
![image](https://user-images.githubusercontent.com/39892654/118993748-5b312300-b9b8-11eb-9a45-56a4b421e277.png)

2.oidc server 直接访问登录页面，没有带returnUrl报错了，是否server端可以自登录呢？
![image](https://user-images.githubusercontent.com/39892654/118994941-5325b300-b9b9-11eb-8bca-6c02d979085b.png)

**Comment by linianhui** [comment]
应该和 #34 有关。
你改下浏览器这个设置试一下：` chrome://flags/#same-site-by-default-cookies`，改成禁用，然后重启浏览器。

**Comment by langhaoabcd** [comment]
可以了，谢谢
